name: Notif Service CI

on:
  push:
    branches: [dev, main]
    paths:
      - 'notif_service/**'
      - '.github/workflows/notif_service.yml'
  pull_request:
    branches: [dev, main]
    paths:
      - 'notif_service/**'
      - '.github/workflows/notif_service.yml'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: notif_service

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install (uses package-lock)
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Coverage report
        run: npm test -- --coverage
